repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-toml
      - id: check-yaml
        args: [--allow-multiple-documents]

  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.6
    hooks:
      - id: codespell

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.10
    hooks:
      - id: ruff-format
        name: ruff-format
        entry: uv run ruff format src tests
        language: system
        types: [python]
        require_serial: true
        pass_filenames: false

      - id: ruff-check
        name: ruff-check
        entry: uv run ruff check --fix src tests
        language: system
        types: [python]
        pass_filenames: false

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.15.0
    hooks:
      - id: mypy
        name: mypy
        entry: uv run mypy --config-file pyproject.toml
        language: system
        types: [python]
        pass_filenames: false

  - repo: https://github.com/PyCQA/bandit
    rev: 1.8.3
    hooks:
      - id: bandit
        name: bandit
        entry: bandit
        language: python
        types: [python]
        exclude: tests
        require_serial: true
